/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package indovina.la.parola;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.*;
import java.awt.event.*;


/**
 *
 * @author jcmaxwell
 */
public class Impiccato extends javax.swing.JFrame {

    /**
     * Creates new form Impiccato
     */
    
    
    public Impiccato() {
        initComponents();
        
        /*JTextField[] P = new JTextField[14];
        this.setLayout(null);
        for (int i = 0; i < 14; i++) {
            
            P[i] = new JTextField("0");
            this.add(P[i]);
            P[i].setBounds(10 + (15 * i), 50, 40, 30);
        }*/
        
    }
    
    int casuale;
    String parola=" ";
    int errore=0;
    int contErrore=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vittoria = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        Inizia = new javax.swing.JButton();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Guess = new javax.swing.JLabel();
        aiuto = new javax.swing.JLabel();
        estrazione = new javax.swing.JLabel();
        lungezza = new javax.swing.JLabel();
        Guess1 = new javax.swing.JLabel();
        Guess2 = new javax.swing.JLabel();
        Guess3 = new javax.swing.JLabel();
        Guess4 = new javax.swing.JLabel();
        Guess5 = new javax.swing.JLabel();
        Guess6 = new javax.swing.JLabel();
        Guess7 = new javax.swing.JLabel();
        Guess8 = new javax.swing.JLabel();
        Guess9 = new javax.swing.JLabel();
        Guess10 = new javax.swing.JLabel();
        Guess11 = new javax.swing.JLabel();
        Guess12 = new javax.swing.JLabel();
        Guess13 = new javax.swing.JLabel();
        GuessParola = new javax.swing.JTextField();
        checkParola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(652, 452));

        jPanel1.setBackground(java.awt.Color.orange);
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 450));

        Inizia.setText("START");
        Inizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniziaActionPerformed(evt);
            }
        });

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });

        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });

        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });

        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });

        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });

        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });

        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });

        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });

        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });

        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });

        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });

        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });

        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });

        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });

        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });

        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });

        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });

        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });

        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCEGLI UNA LETTERA");

        Guess.setForeground(new java.awt.Color(255, 255, 255));
        Guess.setText("_");

        aiuto.setForeground(new java.awt.Color(255, 255, 255));
        aiuto.setText("La parola è lunga:");

        estrazione.setText("Verifica");

        lungezza.setForeground(new java.awt.Color(255, 255, 255));
        lungezza.setText("Lunghezza");
        lungezza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Guess1.setForeground(new java.awt.Color(255, 255, 255));
        Guess1.setText("_");

        Guess2.setForeground(new java.awt.Color(255, 255, 255));
        Guess2.setText("_");

        Guess3.setForeground(new java.awt.Color(255, 255, 255));
        Guess3.setText("_");

        Guess4.setForeground(new java.awt.Color(255, 255, 255));
        Guess4.setText("_");

        Guess5.setForeground(new java.awt.Color(255, 255, 255));
        Guess5.setText("_");

        Guess6.setForeground(new java.awt.Color(255, 255, 255));
        Guess6.setText("_");

        Guess7.setForeground(new java.awt.Color(255, 255, 255));
        Guess7.setText("_");

        Guess8.setForeground(new java.awt.Color(255, 255, 255));
        Guess8.setText("_");

        Guess9.setForeground(new java.awt.Color(255, 255, 255));
        Guess9.setText("_");

        Guess10.setForeground(new java.awt.Color(255, 255, 255));
        Guess10.setText("_");

        Guess11.setForeground(new java.awt.Color(255, 255, 255));
        Guess11.setText("_");

        Guess12.setForeground(new java.awt.Color(255, 255, 255));
        Guess12.setText("_");

        Guess13.setForeground(new java.awt.Color(255, 255, 255));
        Guess13.setText("_");

        GuessParola.setText("PAROLA");

        checkParola.setText("controlla");
        checkParola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkParolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Inizia)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(H)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(I)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aiuto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(O)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(P)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Q)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(R)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(S)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(T))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(estrazione)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(V)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(W)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(X)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Y))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(checkParola))
                                                .addComponent(GuessParola, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Z)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lungezza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(Guess)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guess13)
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inizia)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C)
                    .addComponent(D)
                    .addComponent(E)
                    .addComponent(F)
                    .addComponent(G))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H)
                    .addComponent(I)
                    .addComponent(J)
                    .addComponent(K)
                    .addComponent(L)
                    .addComponent(M)
                    .addComponent(N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(O)
                    .addComponent(P)
                    .addComponent(Q)
                    .addComponent(R)
                    .addComponent(S)
                    .addComponent(T)
                    .addComponent(U))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(V)
                    .addComponent(W)
                    .addComponent(X)
                    .addComponent(Y)
                    .addComponent(Z))
                .addGap(18, 18, 18)
                .addComponent(estrazione)
                .addGap(38, 38, 38)
                .addComponent(GuessParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkParola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aiuto)
                    .addComponent(Guess)
                    .addComponent(lungezza)
                    .addComponent(Guess1)
                    .addComponent(Guess2)
                    .addComponent(Guess3)
                    .addComponent(Guess4)
                    .addComponent(Guess5)
                    .addComponent(Guess6)
                    .addComponent(Guess7)
                    .addComponent(Guess8)
                    .addComponent(Guess9)
                    .addComponent(Guess10)
                    .addComponent(Guess11)
                    .addComponent(Guess12)
                    .addComponent(Guess13))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniziaActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        Graphics imp=jPanel1.getGraphics();
        Graphics BG=jPanel1.getGraphics();
        int x=650;
        int y=450;
        errore=0;
        contErrore=0;
        
        
        
        /*for(int i=25; i<650; i+=25){
        BG.setColor(Color.white);
        BG.drawLine(0, y-i, x, y-i);
        }*/
        imp.setColor(Color.GRAY);
        imp.fillRect(525, 0, 10, 60);
        imp.fillOval(505, 55, 50, 70);
        
        
        //persona
        imp.setColor(Color.orange);
        imp.fillOval(510, 80, 40, 40);
        imp.fillRoundRect(522, 95, 15, 100, 5, 5);
        //imp.setColor(Color.red);
        imp.drawLine(530, 120, 500, 150);
        imp.drawLine(530, 120, 560, 150);
        imp.drawLine(530, 180, 500, 210);
        imp.drawLine(530, 180, 560, 210);
        
        
        Guess.setText("_");
        Guess1.setText("_");
        Guess2.setText("_");
        Guess3.setText("_");
        Guess4.setText("_");
        Guess5.setText("_");
        Guess6.setText("_");
        Guess7.setText("_");
        Guess8.setText("_");
        Guess9.setText("_");
        Guess10.setText("_");
        Guess11.setText("_");
        Guess12.setText("_");
        Guess13.setText("_");
        
        casuale = (int) (Math.random()* 6 + 1);
        switch (casuale){
            
            case 1:
                parola="cactus";
                estrazione.setText("cactus");
                break;
                
            case 2:
                parola="australopiteco";
                estrazione.setText("australopiteco");
                break;
                
            case 3:
                parola="solstizio";
                estrazione.setText("solstizio");
                break;
                
            case 4:
                parola="cane";
                estrazione.setText("cane");
                break;
            
            case 5:
                parola="gatto";
                estrazione.setText("gatto");
                break;
                
            case 6:
                parola="xilofono";
                estrazione.setText("xilofono");
                break;
        }
        
        int lunghezza=parola.length();
        lungezza.setText(String.valueOf(lunghezza));
        
        //calcolo.setText(String.valueOf(num/0.01));
        
        
    }//GEN-LAST:event_IniziaActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
        boolean trov=false;
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'x'){
                if(i==0){
                Guess.setText("x");
                }
                if(i==1){
                Guess1.setText("x");
                }
                if(i==2){
                Guess2.setText("x");
                }
                if(i==3){
                Guess3.setText("x");
                }
                if(i==4){
                Guess4.setText("x");
                }
                if(i==5){
                Guess5.setText("x");
                }
                if(i==6){
                Guess6.setText("x");
                }
                if(i==7){
                Guess7.setText("x");
                }
                if(i==8){
                Guess8.setText("x");
                }
                if(i==9){
                Guess9.setText("x");
                }
                if(i==10){
                Guess10.setText("x");
                }
                if(i==11){
                Guess11.setText("x");
                }
                if(i==12){
                Guess12.setText("x");
                }
                if(i==13){
                Guess13.setText("x");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'x'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
        
    }//GEN-LAST:event_XActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'c'){
                if(i==0){
                Guess.setText("c");
                }
                if(i==1){
                Guess1.setText("c");
                }
                if(i==2){
                Guess2.setText("c");
                }
                if(i==3){
                Guess3.setText("c");
                }
                if(i==4){
                Guess4.setText("c");
                }
                if(i==5){
                Guess5.setText("c");
                }
                if(i==6){
                Guess6.setText("c");
                }
                if(i==7){
                Guess7.setText("c");
                }
                if(i==8){
                Guess8.setText("c");
                }
                if(i==9){
                Guess9.setText("c");
                }
                if(i==10){
                Guess10.setText("c");
                }
                if(i==11){
                Guess11.setText("c");
                }
                if(i==12){
                Guess12.setText("c");
                }
                if(i==13){
                Guess13.setText("c");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'c'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
        //String lettera="c";
        //Guess.setText(lettera);
        
    }//GEN-LAST:event_CActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'a'){
                if(i==0){
                Guess.setText("a");
                }
                if(i==1){
                Guess1.setText("a");
                }
                if(i==2){
                Guess2.setText("a");
                }
                if(i==3){
                Guess3.setText("a");
                }
                if(i==4){
                Guess4.setText("a");
                }
                if(i==5){
                Guess5.setText("a");
                }
                if(i==6){
                Guess6.setText("a");
                }
                if(i==7){
                Guess7.setText("a");
                }
                if(i==8){
                Guess8.setText("a");
                }
                if(i==9){
                Guess9.setText("a");
                }
                if(i==10){
                Guess10.setText("a");
                }
                if(i==11){
                Guess11.setText("a");
                }
                if(i==12){
                Guess12.setText("a");
                }
                if(i==13){
                Guess13.setText("a");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'a'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'b'){
                if(i==0){
                Guess.setText("b");
                }
                if(i==1){
                Guess1.setText("b");
                }
                if(i==2){
                Guess2.setText("b");
                }
                if(i==3){
                Guess3.setText("b");
                }
                if(i==4){
                Guess4.setText("b");
                }
                if(i==5){
                Guess5.setText("b");
                }
                if(i==6){
                Guess6.setText("b");
                }
                if(i==7){
                Guess7.setText("b");
                }
                if(i==8){
                Guess8.setText("b");
                }
                if(i==9){
                Guess9.setText("b");
                }
                if(i==10){
                Guess10.setText("b");
                }
                if(i==11){
                Guess11.setText("b");
                }
                if(i==12){
                Guess12.setText("b");
                }
                if(i==13){
                Guess13.setText("b");
                }
            }
        }
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'b'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_BActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'd'){
                if(i==0){
                Guess.setText("d");
                }
                if(i==1){
                Guess1.setText("d");
                }
                if(i==2){
                Guess2.setText("d");
                }
                if(i==3){
                Guess3.setText("d");
                }
                if(i==4){
                Guess4.setText("d");
                }
                if(i==5){
                Guess5.setText("d");
                }
                if(i==6){
                Guess6.setText("d");
                }
                if(i==7){
                Guess7.setText("d");
                }
                if(i==8){
                Guess8.setText("d");
                }
                if(i==9){
                Guess9.setText("d");
                }
                if(i==10){
                Guess10.setText("d");
                }
                if(i==11){
                Guess11.setText("d");
                }
                if(i==12){
                Guess12.setText("d");
                }
                if(i==13){
                Guess13.setText("d");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'd'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'e'){
                if(i==0){
                Guess.setText("e");
                }
                if(i==1){
                Guess1.setText("e");
                }
                if(i==2){
                Guess2.setText("e");
                }
                if(i==3){
                Guess3.setText("e");
                }
                if(i==4){
                Guess4.setText("e");
                }
                if(i==5){
                Guess5.setText("e");
                }
                if(i==6){
                Guess6.setText("e");
                }
                if(i==7){
                Guess7.setText("e");
                }
                if(i==8){
                Guess8.setText("e");
                }
                if(i==9){
                Guess9.setText("e");
                }
                if(i==10){
                Guess10.setText("e");
                }
                if(i==11){
                Guess11.setText("e");
                }
                if(i==12){
                Guess12.setText("e");
                }
                if(i==13){
                Guess13.setText("e");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'e'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'f'){
                if(i==0){
                Guess.setText("f");
                }
                if(i==1){
                Guess1.setText("f");
                }
                if(i==2){
                Guess2.setText("f");
                }
                if(i==3){
                Guess3.setText("f");
                }
                if(i==4){
                Guess4.setText("f");
                }
                if(i==5){
                Guess5.setText("f");
                }
                if(i==6){
                Guess6.setText("f");
                }
                if(i==7){
                Guess7.setText("f");
                }
                if(i==8){
                Guess8.setText("f");
                }
                if(i==9){
                Guess9.setText("f");
                }
                if(i==10){
                Guess10.setText("f");
                }
                if(i==11){
                Guess11.setText("f");
                }
                if(i==12){
                Guess12.setText("f");
                }
                if(i==13){
                Guess13.setText("f");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'f'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'g'){
                if(i==0){
                Guess.setText("g");
                }
                if(i==1){
                Guess1.setText("g");
                }
                if(i==2){
                Guess2.setText("g");
                }
                if(i==3){
                Guess3.setText("g");
                }
                if(i==4){
                Guess4.setText("g");
                }
                if(i==5){
                Guess5.setText("g");
                }
                if(i==6){
                Guess6.setText("g");
                }
                if(i==7){
                Guess7.setText("g");
                }
                if(i==8){
                Guess8.setText("g");
                }
                if(i==9){
                Guess9.setText("g");
                }
                if(i==10){
                Guess10.setText("g");
                }
                if(i==11){
                Guess11.setText("g");
                }
                if(i==12){
                Guess12.setText("g");
                }
                if(i==13){
                Guess13.setText("g");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'g'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'h'){
                if(i==0){
                Guess.setText("h");
                }
                if(i==1){
                Guess1.setText("h");
                }
                if(i==2){
                Guess2.setText("h");
                }
                if(i==3){
                Guess3.setText("h");
                }
                if(i==4){
                Guess4.setText("h");
                }
                if(i==5){
                Guess5.setText("h");
                }
                if(i==6){
                Guess6.setText("h");
                }
                if(i==7){
                Guess7.setText("h");
                }
                if(i==8){
                Guess8.setText("h");
                }
                if(i==9){
                Guess9.setText("h");
                }
                if(i==10){
                Guess10.setText("h");
                }
                if(i==11){
                Guess11.setText("h");
                }
                if(i==12){
                Guess12.setText("h");
                }
                if(i==13){
                Guess13.setText("h");
                }
            }
        }
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'h'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_HActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'i'){
                if(i==0){
                Guess.setText("i");
                }
                if(i==1){
                Guess1.setText("i");
                }
                if(i==2){
                Guess2.setText("i");
                }
                if(i==3){
                Guess3.setText("i");
                }
                if(i==4){
                Guess4.setText("i");
                }
                if(i==5){
                Guess5.setText("i");
                }
                if(i==6){
                Guess6.setText("i");
                }
                if(i==7){
                Guess7.setText("i");
                }
                if(i==8){
                Guess8.setText("i");
                }
                if(i==9){
                Guess9.setText("i");
                }
                if(i==10){
                Guess10.setText("i");
                }
                if(i==11){
                Guess11.setText("i");
                }
                if(i==12){
                Guess12.setText("i");
                }
                if(i==13){
                Guess13.setText("i");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'i'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_IActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'j'){
                if(i==0){
                Guess.setText("j");
                }
                if(i==1){
                Guess1.setText("j");
                }
                if(i==2){
                Guess2.setText("j");
                }
                if(i==3){
                Guess3.setText("j");
                }
                if(i==4){
                Guess4.setText("j");
                }
                if(i==5){
                Guess5.setText("j");
                }
                if(i==6){
                Guess6.setText("j");
                }
                if(i==7){
                Guess7.setText("j");
                }
                if(i==8){
                Guess8.setText("j");
                }
                if(i==9){
                Guess9.setText("j");
                }
                if(i==10){
                Guess10.setText("j");
                }
                if(i==11){
                Guess11.setText("j");
                }
                if(i==12){
                Guess12.setText("j");
                }
                if(i==13){
                Guess13.setText("j");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'j'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_JActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'k'){
                if(i==0){
                Guess.setText("k");
                }
                if(i==1){
                Guess1.setText("k");
                }
                if(i==2){
                Guess2.setText("k");
                }
                if(i==3){
                Guess3.setText("k");
                }
                if(i==4){
                Guess4.setText("k");
                }
                if(i==5){
                Guess5.setText("k");
                }
                if(i==6){
                Guess6.setText("k");
                }
                if(i==7){
                Guess7.setText("k");
                }
                if(i==8){
                Guess8.setText("k");
                }
                if(i==9){
                Guess9.setText("k");
                }
                if(i==10){
                Guess10.setText("k");
                }
                if(i==11){
                Guess11.setText("k");
                }
                if(i==12){
                Guess12.setText("k");
                }
                if(i==13){
                Guess13.setText("k");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'k'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_KActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'l'){
                if(i==0){
                Guess.setText("l");
                }
                if(i==1){
                Guess1.setText("l");
                }
                if(i==2){
                Guess2.setText("l");
                }
                if(i==3){
                Guess3.setText("l");
                }
                if(i==4){
                Guess4.setText("l");
                }
                if(i==5){
                Guess5.setText("l");
                }
                if(i==6){
                Guess6.setText("l");
                }
                if(i==7){
                Guess7.setText("l");
                }
                if(i==8){
                Guess8.setText("l");
                }
                if(i==9){
                Guess9.setText("l");
                }
                if(i==10){
                Guess10.setText("l");
                }
                if(i==11){
                Guess11.setText("l");
                }
                if(i==12){
                Guess12.setText("l");
                }
                if(i==13){
                Guess13.setText("l");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'l'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_LActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'm'){
                if(i==0){
                Guess.setText("m");
                }
                if(i==1){
                Guess1.setText("m");
                }
                if(i==2){
                Guess2.setText("m");
                }
                if(i==3){
                Guess3.setText("m");
                }
                if(i==4){
                Guess4.setText("m");
                }
                if(i==5){
                Guess5.setText("m");
                }
                if(i==6){
                Guess6.setText("m");
                }
                if(i==7){
                Guess7.setText("m");
                }
                if(i==8){
                Guess8.setText("m");
                }
                if(i==9){
                Guess9.setText("m");
                }
                if(i==10){
                Guess10.setText("m");
                }
                if(i==11){
                Guess11.setText("m");
                }
                if(i==12){
                Guess12.setText("m");
                }
                if(i==13){
                Guess13.setText("m");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'm'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_MActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'n'){
                if(i==0){
                Guess.setText("n");
                }
                if(i==1){
                Guess1.setText("n");
                }
                if(i==2){
                Guess2.setText("n");
                }
                if(i==3){
                Guess3.setText("n");
                }
                if(i==4){
                Guess4.setText("n");
                }
                if(i==5){
                Guess5.setText("n");
                }
                if(i==6){
                Guess6.setText("n");
                }
                if(i==7){
                Guess7.setText("n");
                }
                if(i==8){
                Guess8.setText("n");
                }
                if(i==9){
                Guess9.setText("n");
                }
                if(i==10){
                Guess10.setText("n");
                }
                if(i==11){
                Guess11.setText("n");
                }
                if(i==12){
                Guess12.setText("n");
                }
                if(i==13){
                Guess13.setText("n");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'n'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_NActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'o'){
                if(i==0){
                Guess.setText("o");
                }
                if(i==1){
                Guess1.setText("o");
                }
                if(i==2){
                Guess2.setText("o");
                }
                if(i==3){
                Guess3.setText("o");
                }
                if(i==4){
                Guess4.setText("o");
                }
                if(i==5){
                Guess5.setText("o");
                }
                if(i==6){
                Guess6.setText("o");
                }
                if(i==7){
                Guess7.setText("o");
                }
                if(i==8){
                Guess8.setText("o");
                }
                if(i==9){
                Guess9.setText("o");
                }
                if(i==10){
                Guess10.setText("o");
                }
                if(i==11){
                Guess11.setText("o");
                }
                if(i==12){
                Guess12.setText("o");
                }
                if(i==13){
                Guess13.setText("o");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'o'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'p'){
                if(i==0){
                Guess.setText("p");
                }
                if(i==1){
                Guess1.setText("p");
                }
                if(i==2){
                Guess2.setText("p");
                }
                if(i==3){
                Guess3.setText("p");
                }
                if(i==4){
                Guess4.setText("p");
                }
                if(i==5){
                Guess5.setText("p");
                }
                if(i==6){
                Guess6.setText("p");
                }
                if(i==7){
                Guess7.setText("p");
                }
                if(i==8){
                Guess8.setText("p");
                }
                if(i==9){
                Guess9.setText("p");
                }
                if(i==10){
                Guess10.setText("p");
                }
                if(i==11){
                Guess11.setText("p");
                }
                if(i==12){
                Guess12.setText("p");
                }
                if(i==13){
                Guess13.setText("p");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'p'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_PActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'q'){
                if(i==0){
                Guess.setText("q");
                }
                if(i==1){
                Guess1.setText("q");
                }
                if(i==2){
                Guess2.setText("q");
                }
                if(i==3){
                Guess3.setText("q");
                }
                if(i==4){
                Guess4.setText("q");
                }
                if(i==5){
                Guess5.setText("q");
                }
                if(i==6){
                Guess6.setText("q");
                }
                if(i==7){
                Guess7.setText("q");
                }
                if(i==8){
                Guess8.setText("q");
                }
                if(i==9){
                Guess9.setText("q");
                }
                if(i==10){
                Guess10.setText("q");
                }
                if(i==11){
                Guess11.setText("q");
                }
                if(i==12){
                Guess12.setText("q");
                }
                if(i==13){
                Guess13.setText("q");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'q'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_QActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'r'){
                if(i==0){
                Guess.setText("r");
                }
                if(i==1){
                Guess1.setText("r");
                }
                if(i==2){
                Guess2.setText("r");
                }
                if(i==3){
                Guess3.setText("r");
                }
                if(i==4){
                Guess4.setText("r");
                }
                if(i==5){
                Guess5.setText("r");
                }
                if(i==6){
                Guess6.setText("r");
                }
                if(i==7){
                Guess7.setText("r");
                }
                if(i==8){
                Guess8.setText("r");
                }
                if(i==9){
                Guess9.setText("r");
                }
                if(i==10){
                Guess10.setText("r");
                }
                if(i==11){
                Guess11.setText("r");
                }
                if(i==12){
                Guess12.setText("r");
                }
                if(i==13){
                Guess13.setText("r");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'r'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_RActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 's'){
                if(i==0){
                Guess.setText("s");
                }
                if(i==1){
                Guess1.setText("s");
                }
                if(i==2){
                Guess2.setText("s");
                }
                if(i==3){
                Guess3.setText("s");
                }
                if(i==4){
                Guess4.setText("s");
                }
                if(i==5){
                Guess5.setText("s");
                }
                if(i==6){
                Guess6.setText("s");
                }
                if(i==7){
                Guess7.setText("s");
                }
                if(i==8){
                Guess8.setText("s");
                }
                if(i==9){
                Guess9.setText("s");
                }
                if(i==10){
                Guess10.setText("s");
                }
                if(i==11){
                Guess11.setText("s");
                }
                if(i==12){
                Guess12.setText("s");
                }
                if(i==13){
                Guess13.setText("s");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 's'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_SActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 't'){
                if(i==0){
                Guess.setText("t");
                }
                if(i==1){
                Guess1.setText("t");
                }
                if(i==2){
                Guess2.setText("t");
                }
                if(i==3){
                Guess3.setText("t");
                }
                if(i==4){
                Guess4.setText("t");
                }
                if(i==5){
                Guess5.setText("t");
                }
                if(i==6){
                Guess6.setText("t");
                }
                if(i==7){
                Guess7.setText("t");
                }
                if(i==8){
                Guess8.setText("t");
                }
                if(i==9){
                Guess9.setText("t");
                }
                if(i==10){
                Guess10.setText("t");
                }
                if(i==11){
                Guess11.setText("t");
                }
                if(i==12){
                Guess12.setText("t");
                }
                if(i==13){
                Guess13.setText("t");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 't'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_TActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'u'){
                if(i==0){
                Guess.setText("u");
                }
                if(i==1){
                Guess1.setText("u");
                }
                if(i==2){
                Guess2.setText("u");
                }
                if(i==3){
                Guess3.setText("u");
                }
                if(i==4){
                Guess4.setText("u");
                }
                if(i==5){
                Guess5.setText("u");
                }
                if(i==6){
                Guess6.setText("u");
                }
                if(i==7){
                Guess7.setText("u");
                }
                if(i==8){
                Guess8.setText("u");
                }
                if(i==9){
                Guess9.setText("u");
                }
                if(i==10){
                Guess10.setText("u");
                }
                if(i==11){
                Guess11.setText("u");
                }
                if(i==12){
                Guess12.setText("u");
                }
                if(i==13){
                Guess13.setText("u");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'u'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'v'){
                if(i==0){
                Guess.setText("v");
                }
                if(i==1){
                Guess1.setText("v");
                }
                if(i==2){
                Guess2.setText("v");
                }
                if(i==3){
                Guess3.setText("v");
                }
                if(i==4){
                Guess4.setText("v");
                }
                if(i==5){
                Guess5.setText("v");
                }
                if(i==6){
                Guess6.setText("v");
                }
                if(i==7){
                Guess7.setText("v");
                }
                if(i==8){
                Guess8.setText("v");
                }
                if(i==9){
                Guess9.setText("v");
                }
                if(i==10){
                Guess10.setText("v");
                }
                if(i==11){
                Guess11.setText("v");
                }
                if(i==12){
                Guess12.setText("v");
                }
                if(i==13){
                Guess13.setText("v");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'v'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_VActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'w'){
                if(i==0){
                Guess.setText("w");
                }
                if(i==1){
                Guess1.setText("w");
                }
                if(i==2){
                Guess2.setText("w");
                }
                if(i==3){
                Guess3.setText("w");
                }
                if(i==4){
                Guess4.setText("w");
                }
                if(i==5){
                Guess5.setText("w");
                }
                if(i==6){
                Guess6.setText("w");
                }
                if(i==7){
                Guess7.setText("w");
                }
                if(i==8){
                Guess8.setText("w");
                }
                if(i==9){
                Guess9.setText("w");
                }
                if(i==10){
                Guess10.setText("w");
                }
                if(i==11){
                Guess11.setText("w");
                }
                if(i==12){
                Guess12.setText("w");
                }
                if(i==13){
                Guess13.setText("w");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'w'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_WActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'y'){
                if(i==0){
                Guess.setText("y");
                }
                if(i==1){
                Guess1.setText("y");
                }
                if(i==2){
                Guess2.setText("y");
                }
                if(i==3){
                Guess3.setText("y");
                }
                if(i==4){
                Guess4.setText("y");
                }
                if(i==5){
                Guess5.setText("y");
                }
                if(i==6){
                Guess6.setText("y");
                }
                if(i==7){
                Guess7.setText("y");
                }
                if(i==8){
                Guess8.setText("y");
                }
                if(i==9){
                Guess9.setText("y");
                }
                if(i==10){
                Guess10.setText("y");
                }
                if(i==11){
                Guess11.setText("y");
                }
                if(i==12){
                Guess12.setText("y");
                }
                if(i==13){
                Guess13.setText("y");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'y'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_YActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) == 'z'){
                if(i==0){
                Guess.setText("z");
                }
                if(i==1){
                Guess1.setText("z");
                }
                if(i==2){
                Guess2.setText("z");
                }
                if(i==3){
                Guess3.setText("z");
                }
                if(i==4){
                Guess4.setText("z");
                }
                if(i==5){
                Guess5.setText("z");
                }
                if(i==6){
                Guess6.setText("z");
                }
                if(i==7){
                Guess7.setText("z");
                }
                if(i==8){
                Guess8.setText("z");
                }
                if(i==9){
                Guess9.setText("z");
                }
                if(i==10){
                Guess10.setText("z");
                }
                if(i==11){
                Guess11.setText("z");
                }
                if(i==12){
                Guess12.setText("z");
                }
                if(i==13){
                Guess13.setText("z");
                }
            }
        }
        
        for(int i=0; i<parola.length(); i++){
            if(parola.charAt(i) != 'z'){
                errore++;
            }else{
                errore-=20;
            }
        }
        
        Graphics imp=jPanel1.getGraphics();
            if (errore>0){
                contErrore++;
            
                if(contErrore==1){
                    imp.setColor(Color.BLACK);
                    imp.fillOval(510, 80, 40, 40);
                }
                if(contErrore==2){
                    imp.fillRoundRect(522, 95, 15, 100, 5, 5);
                }
                if(contErrore==3){
                    imp.drawLine(530, 120, 500, 150);
                }
                if(contErrore==4){
                    imp.drawLine(530, 120, 560, 150);
                }
                if(contErrore==5){
                    imp.drawLine(530, 180, 500, 210);
                }
                if(contErrore==6){
                    imp.drawLine(530, 180, 560, 210);
                }
            }
    }//GEN-LAST:event_ZActionPerformed

    private void checkParolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkParolaActionPerformed
        // TODO add your handling code here:
        String Ind;
        Ind=GuessParola.getText();
        if(parola.equals(Ind)){
            vittoria.showMessageDialog(this, "Vittoria");
        }else{
            vittoria.showMessageDialog(this, "Sbagliato");
        }
    }//GEN-LAST:event_checkParolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impiccato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impiccato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impiccato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impiccato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impiccato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JLabel Guess;
    private javax.swing.JLabel Guess1;
    private javax.swing.JLabel Guess10;
    private javax.swing.JLabel Guess11;
    private javax.swing.JLabel Guess12;
    private javax.swing.JLabel Guess13;
    private javax.swing.JLabel Guess2;
    private javax.swing.JLabel Guess3;
    private javax.swing.JLabel Guess4;
    private javax.swing.JLabel Guess5;
    private javax.swing.JLabel Guess6;
    private javax.swing.JLabel Guess7;
    private javax.swing.JLabel Guess8;
    private javax.swing.JLabel Guess9;
    private javax.swing.JTextField GuessParola;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton Inizia;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JLabel aiuto;
    private javax.swing.JButton checkParola;
    private javax.swing.JLabel estrazione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lungezza;
    private javax.swing.JOptionPane vittoria;
    // End of variables declaration//GEN-END:variables
}
